server:
  port: 9191

spring:
  application:
    name: API-GATWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"    
      routes:
      - id: AUTH-SERVICE
        uri: http://localhost:8082
        predicates:
        - Path=/api/auth/**    
      - id: CONTRACTS-SERVICE
        uri: http://localhost:8070
        predicates:
        - Path=/api/contrats/**
      - id: USER-SERVICE
        uri: http://localhost:9080
        predicates:
        - Path=/api/users/**
      - id: PROPRETY-SERVICE
        uri: http://localhost:8062
        predicates:
        - Path=/api/propreties/**
      - id: OWNERSHIP-SERVICE
        uri: http://localhost:9092
        predicates:
        - Path=/api/contrat/**
      - id: COMPLAINTS-SERVICE
        uri: http://localhost:8088
        predicates:
        - Path=/api/reclamation/**
           
          

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
   